// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: service.proto

package service

import (
	context "context"
	model "happyladysauce/rpc/model"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Student_QueryStudent_FullMethodName         = "/service.student/QueryStudent"
	Student_QueryStudents_FullMethodName        = "/service.student/QueryStudents"
	Student_QueryStudentsStream_FullMethodName  = "/service.student/QueryStudentsStream"
	Student_QueryStudentsStream2_FullMethodName = "/service.student/QueryStudentsStream2"
	Student_QueryStudentsStream3_FullMethodName = "/service.student/QueryStudentsStream3"
)

// StudentClient is the client API for Student service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StudentClient interface {
	// 查询单个学生
	QueryStudent(ctx context.Context, in *QueryStudentRequest, opts ...grpc.CallOption) (*QueryStudentResponse, error)
	// 批量查询学生
	QueryStudents(ctx context.Context, in *StudentIds, opts ...grpc.CallOption) (*QueryStudentResponse, error)
	// 流式批量查询学生
	QueryStudentsStream(ctx context.Context, in *StudentIds, opts ...grpc.CallOption) (grpc.ServerStreamingClient[model.Student], error)
	// 流式查询学生
	QueryStudentsStream2(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StudentId, QueryStudentResponse], error)
	// 流式批量查询学生
	QueryStudentsStream3(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StudentId, model.Student], error)
}

type studentClient struct {
	cc grpc.ClientConnInterface
}

func NewStudentClient(cc grpc.ClientConnInterface) StudentClient {
	return &studentClient{cc}
}

func (c *studentClient) QueryStudent(ctx context.Context, in *QueryStudentRequest, opts ...grpc.CallOption) (*QueryStudentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryStudentResponse)
	err := c.cc.Invoke(ctx, Student_QueryStudent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentClient) QueryStudents(ctx context.Context, in *StudentIds, opts ...grpc.CallOption) (*QueryStudentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryStudentResponse)
	err := c.cc.Invoke(ctx, Student_QueryStudents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentClient) QueryStudentsStream(ctx context.Context, in *StudentIds, opts ...grpc.CallOption) (grpc.ServerStreamingClient[model.Student], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Student_ServiceDesc.Streams[0], Student_QueryStudentsStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StudentIds, model.Student]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Student_QueryStudentsStreamClient = grpc.ServerStreamingClient[model.Student]

func (c *studentClient) QueryStudentsStream2(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StudentId, QueryStudentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Student_ServiceDesc.Streams[1], Student_QueryStudentsStream2_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StudentId, QueryStudentResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Student_QueryStudentsStream2Client = grpc.ClientStreamingClient[StudentId, QueryStudentResponse]

func (c *studentClient) QueryStudentsStream3(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StudentId, model.Student], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Student_ServiceDesc.Streams[2], Student_QueryStudentsStream3_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StudentId, model.Student]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Student_QueryStudentsStream3Client = grpc.BidiStreamingClient[StudentId, model.Student]

// StudentServer is the server API for Student service.
// All implementations must embed UnimplementedStudentServer
// for forward compatibility.
type StudentServer interface {
	// 查询单个学生
	QueryStudent(context.Context, *QueryStudentRequest) (*QueryStudentResponse, error)
	// 批量查询学生
	QueryStudents(context.Context, *StudentIds) (*QueryStudentResponse, error)
	// 流式批量查询学生
	QueryStudentsStream(*StudentIds, grpc.ServerStreamingServer[model.Student]) error
	// 流式查询学生
	QueryStudentsStream2(grpc.ClientStreamingServer[StudentId, QueryStudentResponse]) error
	// 流式批量查询学生
	QueryStudentsStream3(grpc.BidiStreamingServer[StudentId, model.Student]) error
	mustEmbedUnimplementedStudentServer()
}

// UnimplementedStudentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStudentServer struct{}

func (UnimplementedStudentServer) QueryStudent(context.Context, *QueryStudentRequest) (*QueryStudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryStudent not implemented")
}
func (UnimplementedStudentServer) QueryStudents(context.Context, *StudentIds) (*QueryStudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryStudents not implemented")
}
func (UnimplementedStudentServer) QueryStudentsStream(*StudentIds, grpc.ServerStreamingServer[model.Student]) error {
	return status.Errorf(codes.Unimplemented, "method QueryStudentsStream not implemented")
}
func (UnimplementedStudentServer) QueryStudentsStream2(grpc.ClientStreamingServer[StudentId, QueryStudentResponse]) error {
	return status.Errorf(codes.Unimplemented, "method QueryStudentsStream2 not implemented")
}
func (UnimplementedStudentServer) QueryStudentsStream3(grpc.BidiStreamingServer[StudentId, model.Student]) error {
	return status.Errorf(codes.Unimplemented, "method QueryStudentsStream3 not implemented")
}
func (UnimplementedStudentServer) mustEmbedUnimplementedStudentServer() {}
func (UnimplementedStudentServer) testEmbeddedByValue()                 {}

// UnsafeStudentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StudentServer will
// result in compilation errors.
type UnsafeStudentServer interface {
	mustEmbedUnimplementedStudentServer()
}

func RegisterStudentServer(s grpc.ServiceRegistrar, srv StudentServer) {
	// If the following call pancis, it indicates UnimplementedStudentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Student_ServiceDesc, srv)
}

func _Student_QueryStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServer).QueryStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Student_QueryStudent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServer).QueryStudent(ctx, req.(*QueryStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Student_QueryStudents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentIds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServer).QueryStudents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Student_QueryStudents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServer).QueryStudents(ctx, req.(*StudentIds))
	}
	return interceptor(ctx, in, info, handler)
}

func _Student_QueryStudentsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StudentIds)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StudentServer).QueryStudentsStream(m, &grpc.GenericServerStream[StudentIds, model.Student]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Student_QueryStudentsStreamServer = grpc.ServerStreamingServer[model.Student]

func _Student_QueryStudentsStream2_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StudentServer).QueryStudentsStream2(&grpc.GenericServerStream[StudentId, QueryStudentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Student_QueryStudentsStream2Server = grpc.ClientStreamingServer[StudentId, QueryStudentResponse]

func _Student_QueryStudentsStream3_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StudentServer).QueryStudentsStream3(&grpc.GenericServerStream[StudentId, model.Student]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Student_QueryStudentsStream3Server = grpc.BidiStreamingServer[StudentId, model.Student]

// Student_ServiceDesc is the grpc.ServiceDesc for Student service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Student_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.student",
	HandlerType: (*StudentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryStudent",
			Handler:    _Student_QueryStudent_Handler,
		},
		{
			MethodName: "QueryStudents",
			Handler:    _Student_QueryStudents_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueryStudentsStream",
			Handler:       _Student_QueryStudentsStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "QueryStudentsStream2",
			Handler:       _Student_QueryStudentsStream2_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "QueryStudentsStream3",
			Handler:       _Student_QueryStudentsStream3_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
